import 'package:flutter/material.dart';
// double totalCartAmount=0;
















String homeNav = "assets/icons/home.png";
String categoryNav = "assets/icons/menu.png";

Color homeColorNav = Colors.black;
Color menuColorNav = Colors.black;
int currentIndex = 0;

// bool themeColor = false;
bool newValue = true;
bool bottomNavRes = false;

List categories = [
  {"name": "Ramadan", "image": "aasets/images/ramadan2.png"},
  {"name": "Ramadan", "image": "aasets/images/ramadan2.png"},
  {"name": "Ramadan", "image": "aasets/images/ramadan2.png"},
  {"name": "Ramadan", "image": "aasets/images/ramadan2.png"},
];
var data={
    "status": 200,
    "message": "Success",
    "ret_str": {
        "cid": "SMART",
        "user_id": "IT22",
        "user_name": "Walid Fahim",
        "user_mobile": "01712429288",
        "user_type": "rep",
        "depot_id": "13-1313",
        "brand_list": [
            {
                "brand_row_id": "2",
                "brand_id": "BG01",
                "brand_name": "Kurkure",
                "brand_image": "http://my.transcombd.com/smart/item/download/sm_product_hierarchy.image_path.a04d391fbe6fa593.a3Vya3VyZS5qcGc%3D.jpg",
                "item_list": [
                    {
                        "item_row_id": "1",
                        "item_id": "40-03-16007",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-03-16007",
                        "item_name": "Kurkure  17 gm    Chilli Chatka",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG02",
                        "flavor_name": "Chilli Chatka",
                        "weight": "17.0",
                        "invoice_price": "7.58",
                        "trade_price": "8.0",
                        "ctn_pcs_ratio": "90",
                        "item_carton": "90",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.844e6ff13ac93079.Q0MxN2cucG5n.png",
                        "item_promo": "Kurkure 17 gm all flavor, Approved Rate: 7.5",
                        "stock_qty": "100",
                        "item_chain": "15",
                        "approved_price": "7.5"
                    },
                    {
                        "item_row_id": "3",
                        "item_id": "40-03-16027",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-03-16027",
                        "item_name": "Kurkure  17 gm    Cream & Onion",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG23",
                        "flavor_name": "Cream & Onion",
                        "weight": "17.0",
                        "invoice_price": "7.58",
                        "trade_price": "8.0",
                        "ctn_pcs_ratio": "90",
                        "item_carton": "90",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.84784dbc253a9d5f.Q08xN2dtLnBuZw%3D%3D.png",
                        "item_promo": "Kurkure 17 gm all flavor, Approved Rate: 7.5",
                        "stock_qty": "5000",
                        "item_chain": "15",
                        "approved_price": "7.5"
                    },
                    {
                        "item_row_id": "2",
                        "item_id": "40-03-46007",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-03-46007",
                        "item_name": "Kurkure  17 gm    Masala Munch",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG03",
                        "flavor_name": "Masala Munch",
                        "weight": "17.0",
                        "invoice_price": "7.58",
                        "trade_price": "8.0",
                        "ctn_pcs_ratio": "90",
                        "item_carton": "90",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.87a4f00a3963cafe.TU0xN2cucG5n.png",
                        "item_promo": "Kurkure 17 gm all flavor, Approved Rate: 7.5",
                        "stock_qty": "200",
                        "item_chain": "15",
                        "approved_price": "7.5"
                    },
                    {
                        "item_row_id": "5",
                        "item_id": "40-03-64042",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-03-64042",
                        "item_name": "Kurkure  17 gm    Spicy Chicken",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG25",
                        "flavor_name": "Spicy Chicken",
                        "weight": "17.0",
                        "invoice_price": "7.58",
                        "trade_price": "8.0",
                        "ctn_pcs_ratio": "90",
                        "item_carton": "90",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.8b180a71d48162ac.U0MxN2cucG5n.png",
                        "item_promo": "Kurkure 17 gm all flavor, Approved Rate: 7.5",
                        "stock_qty": "5000",
                        "item_chain": "15",
                        "approved_price": "7.5"
                    },
                    {
                        "item_row_id": "4",
                        "item_id": "40-03-49007",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-03-49007",
                        "item_name": "Kurkure  17gm    Naughty Tomato",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG24",
                        "flavor_name": "Naughty Tomato",
                        "weight": "17.0",
                        "invoice_price": "7.58",
                        "trade_price": "8.0",
                        "ctn_pcs_ratio": "90",
                        "item_carton": "90",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.ba50e76e1cfdf6a2.TlQxN2cucG5n.png",
                        "item_promo": "Kurkure 17 gm all flavor, Approved Rate: 7.5",
                        "stock_qty": "5000",
                        "item_chain": "15",
                        "approved_price": "7.5"
                    },
                    {
                        "item_row_id": "14",
                        "item_id": "40-03-10025",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-03-10025",
                        "item_name": "Kurkure 37gm  Spicy Chicken",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG25",
                        "flavor_name": "Spicy Chicken",
                        "weight": "37.0",
                        "invoice_price": "18.96",
                        "trade_price": "20.0",
                        "ctn_pcs_ratio": "78",
                        "item_carton": "78",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.97bc176e5c917525.U0MzN2dtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "13",
                        "approved_price": "20.0"
                    },
                    {
                        "item_row_id": "11",
                        "item_id": "40-03-10021",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-03-10021",
                        "item_name": "Kurkure 37gm Chilli Chatka",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG02",
                        "flavor_name": "Chilli Chatka",
                        "weight": "37.0",
                        "invoice_price": "18.96",
                        "trade_price": "20.0",
                        "ctn_pcs_ratio": "78",
                        "item_carton": "78",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.bacf73a8f5318770.Q0MzN2dtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "13",
                        "approved_price": "20.0"
                    },
                    {
                        "item_row_id": "12",
                        "item_id": "40-03-10023",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-03-10023",
                        "item_name": "Kurkure 37gm Cream & Onion",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG23",
                        "flavor_name": "Cream & Onion",
                        "weight": "37.0",
                        "invoice_price": "18.96",
                        "trade_price": "20.0",
                        "ctn_pcs_ratio": "78",
                        "item_carton": "78",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.a990310b0bf6ab4f.Q08zN2dtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "13",
                        "approved_price": "20.0"
                    },
                    {
                        "item_row_id": "13",
                        "item_id": "40-03-10022",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-03-10022",
                        "item_name": "Kurkure 37gm Masala Munch",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG03",
                        "flavor_name": "Masala Munch",
                        "weight": "37.0",
                        "invoice_price": "18.96",
                        "trade_price": "20.0",
                        "ctn_pcs_ratio": "78",
                        "item_carton": "78",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.abd6824784d37187.TU0zN2dtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "13",
                        "approved_price": "20.0"
                    },
                    {
                        "item_row_id": "15",
                        "item_id": "40-03-10024",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-03-10024",
                        "item_name": "Kurkure 37gm Naughty Tomato",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG24",
                        "flavor_name": "Naughty Tomato",
                        "weight": "37.0",
                        "invoice_price": "18.96",
                        "trade_price": "20.0",
                        "ctn_pcs_ratio": "78",
                        "item_carton": "78",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.8bf5280c67b381b5.TlQzN2dtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "13",
                        "approved_price": "20.0"
                    },
                    {
                        "item_row_id": "25",
                        "item_id": "40-03-10026",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-03-10026",
                        "item_name": "Kurkure 75gm  Chilli Chatka",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG02",
                        "flavor_name": "Chilli Chatka",
                        "weight": "75.0",
                        "invoice_price": "37.91",
                        "trade_price": "40.0",
                        "ctn_pcs_ratio": "24",
                        "item_carton": "24",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.8a20b26423463351.Q0M3NWdtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "4",
                        "approved_price": "40.0"
                    },
                    {
                        "item_row_id": "21",
                        "item_id": "40-03-10028",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-03-10028",
                        "item_name": "Kurkure 75gm Cream & Onion",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG23",
                        "flavor_name": "Cream & Onion",
                        "weight": "75.0",
                        "invoice_price": "37.91",
                        "trade_price": "40.0",
                        "ctn_pcs_ratio": "24",
                        "item_carton": "24",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.817fac7312854597.Q083NWdtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "4",
                        "approved_price": "40.0"
                    },
                    {
                        "item_row_id": "22",
                        "item_id": "40-03-10027",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-03-10027",
                        "item_name": "Kurkure 75gm Masala Munch",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG03",
                        "flavor_name": "Masala Munch",
                        "weight": "75.0",
                        "invoice_price": "37.91",
                        "trade_price": "40.0",
                        "ctn_pcs_ratio": "24",
                        "item_carton": "24",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.ac8f096031ee72f6.TU03NWdtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "4",
                        "approved_price": "40.0"
                    },
                    {
                        "item_row_id": "23",
                        "item_id": "40-03-10029",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-03-10029",
                        "item_name": "Kurkure 75gm Naughty Tomato",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG24",
                        "flavor_name": "Naughty Tomato",
                        "weight": "75.0",
                        "invoice_price": "37.91",
                        "trade_price": "40.0",
                        "ctn_pcs_ratio": "24",
                        "item_carton": "24",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.af7b8a83c1749cb0.TlQ3NWdtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "4",
                        "approved_price": "40.0"
                    },
                    {
                        "item_row_id": "24",
                        "item_id": "40-03-10030",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-03-10030",
                        "item_name": "Kurkure 75gm Spicy Chicken",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG01",
                        "brand_name": "Kurkure",
                        "type_id": "CG01",
                        "type_name": "Collet",
                        "flavor_id": "FG25",
                        "flavor_name": "Spicy Chicken",
                        "weight": "75.0",
                        "invoice_price": "37.91",
                        "trade_price": "40.0",
                        "ctn_pcs_ratio": "24",
                        "item_carton": "24",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.a22af95f08ab3c97.U0M3NWdtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "4",
                        "approved_price": "40.0"
                    }
                ]
            },
            {
                "brand_row_id": "15",
                "brand_id": "BG02",
                "brand_name": "Lays",
                "brand_image": "http://my.transcombd.com/smart/item/download/sm_product_hierarchy.image_path.ab9d8ad36e384790.bGF5cy5qcGc%3D.jpg",
                "item_list": [
                    {
                        "item_row_id": "26",
                        "item_id": "40-04-10060",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-04-10060",
                        "item_name": "Lays  ASCO 11.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG07",
                        "flavor_name": "American Style Cream & Onion",
                        "weight": "11.5",
                        "invoice_price": "7.68",
                        "trade_price": "8.1",
                        "ctn_pcs_ratio": "96",
                        "item_carton": "96",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.8c1681644e6eab76.QVNDT18xMS01IGdtLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "16",
                        "approved_price": "8.1"
                    },
                    {
                        "item_row_id": "27",
                        "item_id": "40-04-10068",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-04-10068",
                        "item_name": "Lays  ASCO 18gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG07",
                        "flavor_name": "American Style Cream & Onion",
                        "weight": "18.0",
                        "invoice_price": "11.37",
                        "trade_price": "12.0",
                        "ctn_pcs_ratio": "84",
                        "item_carton": "84",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.938d64a6349e8cbc.TVJQIDE1IEFTQ08ucG5n.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "12.0"
                    },
                    {
                        "item_row_id": "28",
                        "item_id": "40-04-10080",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-04-10080",
                        "item_name": "Lays  ASCO 30.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG07",
                        "flavor_name": "American Style Cream & Onion",
                        "weight": "30.5",
                        "invoice_price": "18.96",
                        "trade_price": "20.0",
                        "ctn_pcs_ratio": "50",
                        "item_carton": "50",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.8c30ccfcc4f42fd6.TVJQIDI1IEFTQ08uanBlZw%3D%3D.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "20.0"
                    },
                    {
                        "item_row_id": "29",
                        "item_id": "40-04-10090",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-04-10090",
                        "item_name": "Lays ASCO 61.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG07",
                        "flavor_name": "American Style Cream & Onion",
                        "weight": "61.5",
                        "invoice_price": "38.86",
                        "trade_price": "41.0",
                        "ctn_pcs_ratio": "24",
                        "item_carton": "24",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.9219c2572c125645.TVJQIDUwIEFTQ08uanBlZw%3D%3D.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "41.0"
                    },
                    {
                        "item_row_id": "30",
                        "item_id": "40-04-10095",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-04-10095",
                        "item_name": "Lays ASCO 95gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG07",
                        "flavor_name": "American Style Cream & Onion",
                        "weight": "95.0",
                        "invoice_price": "58.77",
                        "trade_price": "62.0",
                        "ctn_pcs_ratio": "16",
                        "item_carton": "16",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.b2e1a8f8f21e1155.TVJQIDc1IEFTQ08uanBlZw%3D%3D.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "62.0"
                    },
                    {
                        "item_row_id": "31",
                        "item_id": "40-04-16060",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-04-16060",
                        "item_name": "Lays Classic Salted 11.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG08",
                        "flavor_name": "Classic Salted",
                        "weight": "11.5",
                        "invoice_price": "7.68",
                        "trade_price": "8.1",
                        "ctn_pcs_ratio": "96",
                        "item_carton": "96",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.ab96a348ca2d414d.TVJQXzEwX0NTLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "16",
                        "approved_price": "8.1"
                    },
                    {
                        "item_row_id": "32",
                        "item_id": "40-04-16068",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-04-16068",
                        "item_name": "Lays Classic Salted 18gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG08",
                        "flavor_name": "Classic Salted",
                        "weight": "18.0",
                        "invoice_price": "11.37",
                        "trade_price": "12.0",
                        "ctn_pcs_ratio": "84",
                        "item_carton": "84",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.89300ee6d74c0ffd.TVJQIDE1IENTLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "12.0"
                    },
                    {
                        "item_row_id": "33",
                        "item_id": "40-04-16080",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-04-16080",
                        "item_name": "Lays Classic Salted 30.50",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG08",
                        "flavor_name": "Classic Salted",
                        "weight": "30.5",
                        "invoice_price": "18.96",
                        "trade_price": "20.0",
                        "ctn_pcs_ratio": "50",
                        "item_carton": "50",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.8a21b8ac6422b161.TVJQIDI1IENTLmpwZWc%3D.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "20.0"
                    },
                    {
                        "item_row_id": "34",
                        "item_id": "40-04-16090",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-04-16090",
                        "item_name": "Lays Classic Salted 61.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG08",
                        "flavor_name": "Classic Salted",
                        "weight": "61.5",
                        "invoice_price": "38.86",
                        "trade_price": "41.0",
                        "ctn_pcs_ratio": "24",
                        "item_carton": "24",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.aff488df9aff7236.TVJQIDUwIENTLmpwZWc%3D.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "41.0"
                    },
                    {
                        "item_row_id": "35",
                        "item_id": "40-04-16095",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-04-16095",
                        "item_name": "Lays Classic Salted 95gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG08",
                        "flavor_name": "Classic Salted",
                        "weight": "95.0",
                        "invoice_price": "58.77",
                        "trade_price": "62.0",
                        "ctn_pcs_ratio": "16",
                        "item_carton": "16",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.9eb77619a91172bd.TVJQIDc1IENTLmpwZWc%3D.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "62.0"
                    },
                    {
                        "item_row_id": "36",
                        "item_id": "40-04-64060",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-04-64060",
                        "item_name": "Lays STT 11.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG09",
                        "flavor_name": "Spanish Tomato Tango",
                        "weight": "11.5",
                        "invoice_price": "7.68",
                        "trade_price": "8.1",
                        "ctn_pcs_ratio": "96",
                        "item_carton": "96",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.b0f540864f108775.U1RUXzExLTVnbS5wbmc%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "16",
                        "approved_price": "8.1"
                    },
                    {
                        "item_row_id": "37",
                        "item_id": "40-04-64068",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-04-64068",
                        "item_name": "Lays STT 18gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG09",
                        "flavor_name": "Spanish Tomato Tango",
                        "weight": "18.0",
                        "invoice_price": "11.37",
                        "trade_price": "12.0",
                        "ctn_pcs_ratio": "84",
                        "item_carton": "84",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.988cbb65a5a9a77c.TVJQIDE1IFNUVC5wbmc%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "12.0"
                    },
                    {
                        "item_row_id": "38",
                        "item_id": "40-04-64080",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-04-64080",
                        "item_name": "Lays STT 30.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG09",
                        "flavor_name": "Spanish Tomato Tango",
                        "weight": "30.5",
                        "invoice_price": "18.96",
                        "trade_price": "20.0",
                        "ctn_pcs_ratio": "50",
                        "item_carton": "50",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.904554819c6b5dbc.TVJQIDI1IFNUVC5qcGVn.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "20.0"
                    },
                    {
                        "item_row_id": "39",
                        "item_id": "40-04-64090",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-04-64090",
                        "item_name": "Lays STT 61.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG09",
                        "flavor_name": "Spanish Tomato Tango",
                        "weight": "61.5",
                        "invoice_price": "38.86",
                        "trade_price": "41.0",
                        "ctn_pcs_ratio": "24",
                        "item_carton": "24",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.a3b634cf26327b63.TVJQIDUwIFNUVC5qcGVn.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "41.0"
                    },
                    {
                        "item_row_id": "40",
                        "item_id": "40-04-64095",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-04-64095",
                        "item_name": "Lays STT 95gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG09",
                        "flavor_name": "Spanish Tomato Tango",
                        "weight": "95.0",
                        "invoice_price": "58.77",
                        "trade_price": "62.0",
                        "ctn_pcs_ratio": "16",
                        "item_carton": "16",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.ba118fc333b1b3f9.TVJQIDc1IFNUVC5qcGVn.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "62.0"
                    },
                    {
                        "item_row_id": "41",
                        "item_id": "40-04-67060",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-04-67060",
                        "item_name": "Lays TSSC 11.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG27",
                        "flavor_name": "Thai Style Spicy Chicken",
                        "weight": "11.5",
                        "invoice_price": "7.68",
                        "trade_price": "8.1",
                        "ctn_pcs_ratio": "96",
                        "item_carton": "96",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.99ea184f873b0888.VFNTQ18xMS01Z20ucG5n.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "16",
                        "approved_price": "8.1"
                    },
                    {
                        "item_row_id": "42",
                        "item_id": "40-04-67068",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-04-67068",
                        "item_name": "Lays TSSC 18gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG27",
                        "flavor_name": "Thai Style Spicy Chicken",
                        "weight": "18.0",
                        "invoice_price": "11.37",
                        "trade_price": "12.0",
                        "ctn_pcs_ratio": "84",
                        "item_carton": "84",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.8ab51dd93f258c38.TVJQIDE1IFRTU0MucG5n.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "12.0"
                    },
                    {
                        "item_row_id": "43",
                        "item_id": "40-04-67080",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-04-67080",
                        "item_name": "Lays TSSC 30.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG27",
                        "flavor_name": "Thai Style Spicy Chicken",
                        "weight": "30.5",
                        "invoice_price": "18.96",
                        "trade_price": "20.0",
                        "ctn_pcs_ratio": "50",
                        "item_carton": "50",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.a0d06cee1fbc18c0.TVJQIDI1IFRTU0MuanBlZw%3D%3D.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "20.0"
                    },
                    {
                        "item_row_id": "44",
                        "item_id": "40-04-67090",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-04-67090",
                        "item_name": "Lays TSSC 61.50gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG27",
                        "flavor_name": "Thai Style Spicy Chicken",
                        "weight": "61.5",
                        "invoice_price": "38.86",
                        "trade_price": "41.0",
                        "ctn_pcs_ratio": "24",
                        "item_carton": "24",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.b4908ad706ecf731.TVJQIDUwIFRTU0MuanBlZw%3D%3D.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "41.0"
                    },
                    {
                        "item_row_id": "45",
                        "item_id": "40-04-67095",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-04-67095",
                        "item_name": "Lays TSSC 95gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG02",
                        "brand_name": "Lays",
                        "type_id": "CG03",
                        "type_name": "Lays",
                        "flavor_id": "FG27",
                        "flavor_name": "Thai Style Spicy Chicken",
                        "weight": "95.0",
                        "invoice_price": "58.77",
                        "trade_price": "62.0",
                        "ctn_pcs_ratio": "16",
                        "item_carton": "16",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.b4e60896a427acc7.TVJQIDc1IFRTU0MuanBlZw%3D%3D.jpeg",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "62.0"
                    }
                ]
            },
            {
                "brand_row_id": "26",
                "brand_id": "BG03",
                "brand_name": "Oats",
                "brand_image": "http://my.transcombd.com/smart/item/download/sm_product_hierarchy.image_path.913832592ece621f.cXVha2VyLmpwZw%3D%3D.jpg",
                "item_list": [
                    {
                        "item_row_id": "48",
                        "item_id": "40-01-52007",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-01-52007",
                        "item_name": "Quaker Oats  450 gm Jar",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG03",
                        "brand_name": "Oats",
                        "type_id": "CG06",
                        "type_name": "Oats",
                        "flavor_id": "FG15",
                        "flavor_name": "Oats",
                        "weight": "450.0",
                        "invoice_price": "254.53",
                        "trade_price": "268.53",
                        "ctn_pcs_ratio": "20",
                        "item_carton": "20",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.a7d1a78440daab7c.UXVha2VyIDQ1MEcucG5n.png",
                        "item_promo": "",
                        "stock_qty": "0",
                        "item_chain": "1",
                        "approved_price": "268.53"
                    },
                    {
                        "item_row_id": "47",
                        "item_id": "40-01-52025",
                        "item_size": "SMALL",
                        "item_unit": "PCS",
                        "item_code": "40-01-52025",
                        "item_name": "Quaker Oats  500 gm Jar",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG03",
                        "brand_name": "Oats",
                        "type_id": "CG06",
                        "type_name": "Oats",
                        "flavor_id": "FG15",
                        "flavor_name": "Oats",
                        "weight": "500.0",
                        "invoice_price": "255.74",
                        "trade_price": "268.53",
                        "ctn_pcs_ratio": "20",
                        "item_carton": "20",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.9eca1977722dd39c.UXVha2VyIDQ1MEcucG5n.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "268.53"
                    },
                    {
                        "item_row_id": "49",
                        "item_id": "40-01-52006",
                        "item_size": "LARGE",
                        "item_unit": "PCS",
                        "item_code": "40-01-52006",
                        "item_name": "Quaker Oats  900gm",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG03",
                        "brand_name": "Oats",
                        "type_id": "CG06",
                        "type_name": "Oats",
                        "flavor_id": "FG15",
                        "flavor_name": "Oats",
                        "weight": "900.0",
                        "invoice_price": "478.72",
                        "trade_price": "502.66",
                        "ctn_pcs_ratio": "12",
                        "item_carton": "12",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.8e872f0f1a4a1a2d.UXVha2VyOTAwRy5wbmc%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "502.66"
                    },
                    {
                        "item_row_id": "46",
                        "item_id": "40-06-52115",
                        "item_size": "MEDIUM",
                        "item_unit": "PCS",
                        "item_code": "40-06-52115",
                        "item_name": "Quaker Whole Oats 700 gm Jar",
                        "company_id": "MG01",
                        "company_name": "TCPL Products",
                        "brand_id": "BG03",
                        "brand_name": "Oats",
                        "type_id": "CG06",
                        "type_name": "Oats",
                        "flavor_id": "FG15",
                        "flavor_name": "Oats",
                        "weight": "700.0",
                        "invoice_price": "403.6",
                        "trade_price": "423.78",
                        "ctn_pcs_ratio": "12",
                        "item_carton": "12",
                        "sequence_no": "1",
                        "stock_cover_days": "7",
                        "item_vat": "0.0",
                        "item_avatar": "http://my.transcombd.com/smart/item/download/sm_item.image_path.a78d8786bb2fc37f.V2hvbGVPYXRzLnBuZw%3D%3D.png",
                        "item_promo": "",
                        "stock_qty": "5000",
                        "item_chain": "1",
                        "approved_price": "423.78"
                    }
                ]
            }
        ]
    }
};

List noodles = [
  {
    "price": "20BDT",
    "name": "Cocola Egg Noodles",
    "quantity": "130 gm",
    "imageName": "assets/images/chaldal-premium-beef.webp",
    "details":
        "Protein, calcium, iodine and vitamin enriched egg noodles.Ingredients: Noodles: Spices, iodized salt, water. Masala: Iodized salt, tasting salt, corn starch, chicken powder, sugar, egg powder, chili powder, tapioca starch, citric acid. Nutrition: Minerals, fibre, calorie, protein, fat, carbohydrate, calcium, iron, carotene, vitamin B-1, vitamin B-2.",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "160BDT",
    "name": "Nestle Maggie 2-Minute Masala Noodles",
    "quantity": "8 pack",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        " MAGGI offers tasty and healthy snacks option for Bangladeshi families Fortified with Vitamin A, Iron and Iodine./n The tastemaker is comprised of known ingredients typically found in Bangladeshi households, such as turmeric, pepper, coriander, ginger and cardamom.To boost the goodness in your bowl, add colourful vegetables and lean protein such as chicken.Contains noodle cake & Tastemaker inside for a quick 2-minute preparation ",
    "variant": "Masala",
    "net-weight": "496g",
    "origin": "Bangladesh"
  },
  {
    "price": "20BDT",
    "name": "Doodles Stick Noodles",
    "quantity": "150 gm",
    "imageName": "assets/images/beef-front-leg-bone.jpg",
    "details":
        "Doodles instant noodles gives your fussy eating kids something tasty to look forward to. Kids’ love the irresistible taste of Doodles instant noodles that kills their boredom and provides iron, iodine, calcium and many other nutrient",
    "variant": "",
    "net-weight": "",
    "origin": "Bangladesh"
  },
  {
    "price": "65BDT",
    "name": "Sajib Coook Noodles Chicken Tandoori 8 Pcs",
    "quantity": "300 gm",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "180BDT",
    "name": "Nestle Maggie Masala Blast Noodles",
    "quantity": "8 pack",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
];

List freshFruits = [
  {
    "price": "115 BDT",
    "name": "Black Grapes",
    "quantity": "250 gm",
    "imageName": "assets/images/chaldal-premium-beef.webp",
    "details":
        "Protein, calcium, iodine and vitamin enriched egg noodles.Ingredients: Noodles: Spices, iodized salt, water. Masala: Iodized salt, tasting salt, corn starch, chicken powder, sugar, egg powder, chili powder, tapioca starch, citric acid. Nutrition: Minerals, fibre, calorie, protein, fat, carbohydrate, calcium, iron, carotene, vitamin B-1, vitamin B-2.",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "25 BDT",
    "name": "Cherry Pineapple",
    "quantity": "each",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        " MAGGI offers tasty and healthy snacks option for Bangladeshi families Fortified with Vitamin A, Iron and Iodine./n The tastemaker is comprised of known ingredients typically found in Bangladeshi households, such as turmeric, pepper, coriander, ginger and cardamom.To boost the goodness in your bowl, add colourful vegetables and lean protein such as chicken.Contains noodle cake & Tastemaker inside for a quick 2-minute preparation ",
    "variant": "Masala",
    "net-weight": "496g",
    "origin": "Bangladesh"
  },
  {
    "price": "145 BDT",
    "name": "Laal Angur",
    "quantity": "250 gm",
    "imageName": "assets/images/beef-front-leg-bone.jpg",
    "details":
        "Doodles instant noodles gives your fussy eating kids something tasty to look forward to. Kids’ love the irresistible taste of Doodles instant noodles that kills their boredom and provides iron, iodine, calcium and many other nutrient",
    "variant": "",
    "net-weight": "",
    "origin": "Bangladesh"
  },
  {
    "price": "275 BDT",
    "name": "Watermelon Medium 4kg ",
    "quantity": "each",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "185 BDT",
    "name": "Shada Nashpati",
    "quantity": "2 pcs",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
];

List oil = [
  {
    "price": "906 BDT",
    "name": "Teer Fortified Soyabean Oil",
    "quantity": "5 ltr",
    "imageName": "assets/images/chaldal-premium-beef.webp",
    "details":
        "Protein, calcium, iodine and vitamin enriched egg noodles.Ingredients: Noodles: Spices, iodized salt, water. Masala: Iodized salt, tasting salt, corn starch, chicken powder, sugar, egg powder, chili powder, tapioca starch, citric acid. Nutrition: Minerals, fibre, calorie, protein, fat, carbohydrate, calcium, iron, carotene, vitamin B-1, vitamin B-2.",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "374 BDT",
    "name": "Fresh Fortified Soyabean Oil",
    "quantity": "2 ltr",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        " MAGGI offers tasty and healthy snacks option for Bangladeshi families Fortified with Vitamin A, Iron and Iodine./n The tastemaker is comprised of known ingredients typically found in Bangladeshi households, such as turmeric, pepper, coriander, ginger and cardamom.To boost the goodness in your bowl, add colourful vegetables and lean protein such as chicken.Contains noodle cake & Tastemaker inside for a quick 2-minute preparation ",
    "variant": "Masala",
    "net-weight": "496g",
    "origin": "Bangladesh"
  },
  {
    "price": "185 BDT",
    "name": "Radhuni Pure Mustard Oil",
    "quantity": "500 ml",
    "imageName": "assets/images/beef-front-leg-bone.jpg",
    "details":
        "Doodles instant noodles gives your fussy eating kids something tasty to look forward to. Kids’ love the irresistible taste of Doodles instant noodles that kills their boredom and provides iron, iodine, calcium and many other nutrient",
    "variant": "",
    "net-weight": "",
    "origin": "Bangladesh"
  },
  {
    "price": "185 BDT",
    "name": "Teer Fortified Soyabean Oil ",
    "quantity": "1 ltr",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "1620 BDT",
    "name": "Suffola Active Plus Edible oil",
    "quantity": "5 ltr",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
];

List saltNSugar = [
  {
    "price": "120 BDT",
    "name": "Loose White Sugar",
    "quantity": "1 kg",
    "imageName": "assets/images/chaldal-premium-beef.webp",
    "details":
        "Protein, calcium, iodine and vitamin enriched egg noodles.Ingredients: Noodles: Spices, iodized salt, water. Masala: Iodized salt, tasting salt, corn starch, chicken powder, sugar, egg powder, chili powder, tapioca starch, citric acid. Nutrition: Minerals, fibre, calorie, protein, fat, carbohydrate, calcium, iron, carotene, vitamin B-1, vitamin B-2.",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "22 BDT",
    "name": "ACI Pure Salt",
    "quantity": "500 gm",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        " MAGGI offers tasty and healthy snacks option for Bangladeshi families Fortified with Vitamin A, Iron and Iodine./n The tastemaker is comprised of known ingredients typically found in Bangladeshi households, such as turmeric, pepper, coriander, ginger and cardamom.To boost the goodness in your bowl, add colourful vegetables and lean protein such as chicken.Contains noodle cake & Tastemaker inside for a quick 2-minute preparation ",
    "variant": "Masala",
    "net-weight": "496g",
    "origin": "Bangladesh"
  },
  {
    "price": "42 BDT",
    "name": "Fresh Super Premium",
    "quantity": "1 Kg",
    "imageName": "assets/images/beef-front-leg-bone.jpg",
    "details":
        "Doodles instant noodles gives your fussy eating kids something tasty to look forward to. Kids’ love the irresistible taste of Doodles instant noodles that kills their boredom and provides iron, iodine, calcium and many other nutrient",
    "variant": "",
    "net-weight": "",
    "origin": "Bangladesh"
  },
  {
    "price": "55 BDT",
    "name": "Sugar Candy(Tal Misri) ",
    "quantity": "200 gm",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "559 BDT",
    "name": "Sis Brown Sugar",
    "quantity": "800 gm",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
];

List biscuits = [
  {
    "price": "10 BDT",
    "name": "Haque Mr. Cookie Butter",
    "quantity": "39 gm",
    "imageName": "assets/images/chaldal-premium-beef.webp",
    "details":
        "Protein, calcium, iodine and vitamin enriched egg noodles.Ingredients: Noodles: Spices, iodized salt, water. Masala: Iodized salt, tasting salt, corn starch, chicken powder, sugar, egg powder, chili powder, tapioca starch, citric acid. Nutrition: Minerals, fibre, calorie, protein, fat, carbohydrate, calcium, iron, carotene, vitamin B-1, vitamin B-2.",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "15 BDT",
    "name": "Olympic Energy Plus Biscuit",
    "quantity": "62 gm",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        " MAGGI offers tasty and healthy snacks option for Bangladeshi families Fortified with Vitamin A, Iron and Iodine./n The tastemaker is comprised of known ingredients typically found in Bangladeshi households, such as turmeric, pepper, coriander, ginger and cardamom.To boost the goodness in your bowl, add colourful vegetables and lean protein such as chicken.Contains noodle cake & Tastemaker inside for a quick 2-minute preparation ",
    "variant": "Masala",
    "net-weight": "496g",
    "origin": "Bangladesh"
  },
  {
    "price": "20 BDT",
    "name": "Bangas Grand Choice Salted Biscuit",
    "quantity": "70 gm",
    "imageName": "assets/images/beef-front-leg-bone.jpg",
    "details":
        "Doodles instant noodles gives your fussy eating kids something tasty to look forward to. Kids’ love the irresistible taste of Doodles instant noodles that kills their boredom and provides iron, iodine, calcium and many other nutrient",
    "variant": "",
    "net-weight": "",
    "origin": "Bangladesh"
  },
  {
    "price": "20 BDT",
    "name": "Cocola Champion Chocolate biscuit",
    "quantity": "65 gm",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
  {
    "price": "35 BDT",
    "name": "Pran Potata Spicy Biscuit",
    "quantity": "100 gm",
    "imageName": "assets/images/beef-kuruli-bone.jpg",
    "details":
        "MAGGI MASALA BLAST is Yummy and Spicy Noodles especially for the teenagers who love to have hot and spicy foods.Fortified with Vitamin A, Iron and Iodine.This unique tastemaker is comprised of the ingredients that consumers know and love such as red chilli, turmeric, black pepper, onion, ginger and cardamom sourced from both home and abroad.Contains noodle cake & Tastemaker inside for a quick preparation",
    "variant": "Masala blast",
    "net-weight": "504 g",
    "origin": "Bangladesh"
  },
];
